In [2]:
import pandas as pd
from functions import *

In [2]:
months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
year = 2014

In [3]:
test_month = load_month("01", 2014)
print(test_month.shape)
test_month.head()

(2396390, 19)

,contractid,planid,ssa,fips,state,county,enrollment,org_type,plan_type,partd,snp,eghp,org_name,org_marketing_name,plan_name,parent_org,contract_date,month,year
0,E0654,801,61000.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
1,E0654,801,62060.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
2,E0654,801,2198.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
3,E0654,801,2275.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
4,E0654,801,56010.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014

In [4]:
print(test_month.columns.tolist())

['contractid', 'planid', 'ssa', 'fips', 'state', 'county', 'enrollment', 'org_type', 'plan_type', 'partd', 'snp', 'eghp', 'org_name', 'org_marketing_name', 'plan_name', 'parent_org', 'contract_date', 'month', 'year']

In [5]:
test_service = load_month_sa("01", 2014)
print(test_service.shape)
test_service.head()

(397527, 13)

,contractid,org_name,org_type,plan_type,partial,eghp,ssa,fips,county,state,notes,month,year
0,90091,UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT,HCPP - 1833 Cost,HCPP - 1833 Cost,NaN,NaN,NaN,NaN,NaN,NaN,"Covers the entire US, all States and Counties",1,2014
1,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12020.0,15003.0,Honolulu,HI,NaN,1,2014
2,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12040.0,15007.0,Kauai,HI,NaN,1,2014
3,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12050.0,15009.0,Maui,HI,NaN,1,2014
4,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,16510.0,19103.0,Johnson,IA,NaN,1,2014

In [6]:
print(test_service.columns.tolist())

['contractid', 'org_name', 'org_type', 'plan_type', 'partial', 'eghp', 'ssa', 'fips', 'county', 'state', 'notes', 'month', 'year']

In [7]:
plan_list = []

for m in months:
    df = load_month(m, year)
    plan_list.append(df)

plan_data_2014 = pd.concat(plan_list, ignore_index=True)

print(plan_data_2014.shape)
plan_data_2014.head()

(28652477, 19)

,contractid,planid,ssa,fips,state,county,enrollment,org_type,plan_type,partd,snp,eghp,org_name,org_marketing_name,plan_name,parent_org,contract_date,month,year
0,E0654,801,61000.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
1,E0654,801,62060.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
2,E0654,801,2198.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
3,E0654,801,2275.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
4,E0654,801,56010.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014

In [8]:
print(plan_data_2014.columns.tolist())

['contractid', 'planid', 'ssa', 'fips', 'state', 'county', 'enrollment', 'org_type', 'plan_type', 'partd', 'snp', 'eghp', 'org_name', 'org_marketing_name', 'plan_name', 'parent_org', 'contract_date', 'month', 'year']

In [9]:
service_list = []

for m in months:
    df = load_month_sa(m, year)
    service_list.append(df)

service_data_2014 = pd.concat(service_list, ignore_index=True)

print(service_data_2014.shape)
service_data_2014.head()

(4770949, 13)

,contractid,org_name,org_type,plan_type,partial,eghp,ssa,fips,county,state,notes,month,year
0,90091,UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT,HCPP - 1833 Cost,HCPP - 1833 Cost,NaN,NaN,NaN,NaN,NaN,NaN,"Covers the entire US, all States and Counties",1,2014
1,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12020.0,15003.0,Honolulu,HI,NaN,1,2014
2,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12040.0,15007.0,Kauai,HI,NaN,1,2014
3,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12050.0,15009.0,Maui,HI,NaN,1,2014
4,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,16510.0,19103.0,Johnson,IA,NaN,1,2014

In [10]:
print(service_data_2014.columns.tolist())

['contractid', 'org_name', 'org_type', 'plan_type', 'partial', 'eghp', 'ssa', 'fips', 'county', 'state', 'notes', 'month', 'year']

In [3]:
output_path = "/home/sbandl2/econ470/a0/work/econ470-hw2/data/output"

In [12]:
plan_data_2014.to_csv(output_path + "/plan_data_2014.csv", index=False)
service_data_2014.to_csv(output_path + "/service_data_2014.csv", index=False)

print("Saved plan_data_2014.csv")
print("Saved service_data_2014.csv")

Saved plan_data_2014.csv
Saved service_data_2014.csv

In [4]:
plan_data_2014 = pd.read_csv(output_path + "/plan_data_2014.csv")
service_data_2014 = pd.read_csv(output_path + "/service_data_2014.csv")

/tmp/ipykernel_416088/919885174.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  service_data_2014 = pd.read_csv(output_path + "/service_data_2014.csv")

In [5]:
print(plan_data_2014.shape)
print(service_data_2014.shape)

(28652477, 19)
(4770949, 13)

In [6]:
plan_data_2014.head()

,contractid,planid,ssa,fips,state,county,enrollment,org_type,plan_type,partd,snp,eghp,org_name,org_marketing_name,plan_name,parent_org,contract_date,month,year
0,E0654,801,61000.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
1,E0654,801,62060.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
2,E0654,801,2198.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
3,E0654,801,2275.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014
4,E0654,801,56010.0,NaN,NaN,NaN,NaN,Employer/Union Only Direct Contract PDP,Employer/Union Only Direct Contract PDP,Yes,No,Yes,IBT VOLUNTARY EMPLOYEE BENEFITS TRUST,TEAMStar Medicare Part D Prescription Drug Pro...,IBT VEBA (Employer PDP),IBT Voluntary Employee Benefits Trust,01/01/2007,1,2014

In [7]:
service_data_2014.head()

,contractid,org_name,org_type,plan_type,partial,eghp,ssa,fips,county,state,notes,month,year
0,90091,UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT,HCPP - 1833 Cost,HCPP - 1833 Cost,NaN,NaN,NaN,NaN,NaN,NaN,"Covers the entire US, all States and Counties",1,2014
1,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12020.0,15003.0,Honolulu,HI,NaN,1,2014
2,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12040.0,15007.0,Kauai,HI,NaN,1,2014
3,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,12050.0,15009.0,Maui,HI,NaN,1,2014
4,H0028,"CHA HMO, INC.",Local CCP,HMO/HMOPOS,NaN,NaN,16510.0,19103.0,Johnson,IA,NaN,1,2014

In [8]:
print(plan_data_2014.columns.tolist())
print(service_data_2014.columns.tolist())

['contractid', 'planid', 'ssa', 'fips', 'state', 'county', 'enrollment', 'org_type', 'plan_type', 'partd', 'snp', 'eghp', 'org_name', 'org_marketing_name', 'plan_name', 'parent_org', 'contract_date', 'month', 'year']
['contractid', 'org_name', 'org_type', 'plan_type', 'partial', 'eghp', 'ssa', 'fips', 'county', 'state', 'notes', 'month', 'year']

In [ ]:
base_2014 = pd.merge(
    plan_data_2014,
    service_data_2014[["contractid", "month", "year", "ssa", "fips", "county", "state", "partial", "notes"]],
    on=["contractid", "month", "year"],
    how="left",
    suffixes=("", "_service")
)

print(base_2014.shape)
base_2014.head()

In [ ]:
# Fill missing county information from service-area fields
base_2014["state"] = base_2014["state"].fillna(base_2014["state_service"])
base_2014["county"] = base_2014["county"].fillna(base_2014["county_service"])
base_2014["fips"] = base_2014["fips"].fillna(base_2014["fips_service"])
base_2014["ssa"] = base_2014["ssa"].fillna(base_2014["ssa_service"])

In [ ]:
base_2014[["contractid", "planid", "state", "county", "fips", "ssa", "enrollment", "plan_type", "partd", "snp"]].head()

In [ ]:
base_2014[["state", "county", "fips", "ssa"]].isna().sum()

In [ ]:
# Remove SNPs
base_2014 = base_2014[base_2014["snp"] != "Yes"]
print(base_2014.shape)

In [ ]:
# Remove 800-series plans
base_2014 = base_2014[(base_2014["planid"] < 800) | (base_2014["planid"] >= 900)]
print(base_2014.shape)

In [ ]:
# Remove prescription drug only plans
base_2014 = base_2014[base_2014["plan_type"] != "Prescription Drug Plan"]
print(base_2014.shape)

In [ ]:
base_2014.to_csv(output_path + "/base_data_2014.csv", index=False)
print("Saved base_data_2014.csv")